language: julia
julia:
  - 1.4
notifications:
    email: false
services:
    - docker

env:
    - USE_DOCKER=0
    - USE_DOCKER=1

before_script:
    - cp deployment/.env.example deployment/.env
    - if [ ${USE_DOCKER} = 1 ]; then
        docker build -t juliapackaging/pkgserver.jl .;
        make -C deployment up;
        make -C deployment stop-watchtower;
        (make -C deployment logs &);
        export JULIA_PKG_SERVER="http://localhost:8000";
        export JULIA_PKG_SERVER_STORAGE_ROOT=$(pwd)/deployment/storage;
      fi

after_script:
    - if [ ${USE_DOCKER} = 1 ]; then
        make -C deployment destroy;
      fi
