# This is the production docker-compose setup, complete with nginx TLS terminator
version: '2.3'
services:
    loadbalancer:
        image: jonasal/nginx-certbot
        restart: unless-stopped
        environment:
            CERTBOT_EMAIL: "${CERTBOT_EMAIL:-info@foobar.com}"
        # Use `host` network mode so that we get proper ipv6 IP addresses
        network_mode: host
        #ports:
        #    - 80:80/tcp
        #    - 443:443/tcp
        volumes:
            # Mount in our nginx configs
            - ./build/loadbalancer.nginx.conf:/etc/nginx/user_conf.d/loadbalancer-${SERVER_FQDN:-default}.conf
            - ../deployment/conf/optimized.nginx.conf:/etc/nginx/nginx.conf
            # Keep SSL certificates permanently
            - letsencrypt:/etc/letsencrypt
            # Store logs for us to peruse at our leisure
            - ./logs/nginx:/logs
        labels:
            com.centurylinklabs.watchtower.scope: "pkgserver.jl"

    # Auto-reload docker containers when their images are updated
    watchtower:
        image: containrrr/watchtower
        restart: unless-stopped
        volumes:
            # Mount the docker socket
            - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup --scope pkgserver.jl
        labels:
            com.centurylinklabs.watchtower.scope: "pkgserver.jl"

volumes:
    letsencrypt:
