name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  all:
    name: all
    needs: [test, docker-build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All CI jobs have completed."
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - use Docker ${{ matrix.docker }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Keep in sync with pkg-update.yml and the Dockerfile
        julia-version:
          - "1.12"
        os:
          - ubuntu-latest
        docker:
          - 'true'
          - 'false'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@a45e8fa8be21c18a06b7177052533149e61e9b38 # v3.1.0
      - name: Setup Docker
        if: ${{ matrix.docker == 'true' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
          cp deployment/.env.example deployment/.env
          make -C deployment local-build
          make -C deployment up
          make -C deployment stop-watchtower
          (make -C deployment logs &)
          echo "JULIA_PKG_SERVER=http://127.0.0.1:8000" >> ${GITHUB_ENV}
          echo "JULIA_PKG_SERVER_STORAGE_ROOT=$(pwd)/deployment/storage" >> ${GITHUB_ENV}
      - uses: julia-actions/julia-runtest@6e050c8013b833b1195105ff2fce9cd802f53271 # v1.12.0
      - name: Startup time test
        run: |
          julia --project bin/startup_time.jl
      - name: Destroy Docker
        if: ${{ matrix.docker == 'true' }}
        run: |
          make -C deployment destroy
  docker-build:
    name: docker-build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: docker login
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build
        run: docker build -t juliapackaging/pkgserver.jl .
      - name: docker push
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: docker push juliapackaging/pkgserver.jl
